
server:
  port: 8066

spring:
  datasource:
    url: jdbc:h2:mem:base_data
    driver-class-name: org.h2.Driver
    username: loc
    password: loc
    
  h2:
    #    开启console 访问 默认false
    console:
      enabled: true
      settings:
        #      开启h2 console 跟踪 方便调试  默认 false
        trace: true
        #      允许console 远程访问 默认false
        web-allow-others: true
      #  h2 访问路径上下文
      path: /h2

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
