
server:
  port: 8066

spring:
  datasource:
    url: jdbc:h2:mem:base_data
    driver-class-name: org.h2.Driver
    username: loc
    password: loc
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
